proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  port: 8080
  authentication: simple
  admin-groups: admins
  hide-navbar: true
  heartbeat-rate: 10000
  heartbeat-timeout: 20000
  container-wait-time: 20000
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true  
  specs:
  - id: regresion
    display-name: Regresion Mini
    description: Is a regression with minimun resource, is a demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "options(tz='America/Edmonton');shiny::runApp('/home/app', port = 3838, host = '0.0.0.0')"]
    container-image: x0cristianx0/mini
    container-network: sp-example-net
  - id: Grafica
    display-name: Condicional Nutritional
    description: Determine the condicional nutritional of the people
    container-cmd: ["R", "-e", "shiny::runApp('/grafico/', host='0.0.0.0', port= 3838)"]
    container-image: x0cristianx0/grafica_oms
    container-network: sp-example-net
  - id: texto
    display-name: Predict Text
    description: Predict the next word and probability the next words
    container-cmd: ["R", "-e", "shiny::runApp('/build_zone/', host='0.0.0.0', port=3838)"]
    container-image: x0cristianx0/texto
    container-network: sp-example-net
logging:
  file:
    shinyproxy.log
#sudo docker run -v /var/run/docker.sock:/var/run/docker.sock:ro --group-add $(getent group docker | cut -d: -f3) --net sp-example-net -p 8080:8080 mi_shinyproxy